version: '3'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    ports:
      - "80:80"

    expose:
      - 80
    volumes:
      - ~/web/html:/usr/share/nginx/html
      - ~/nginx/nginx.conf/:/etc/nginx/conf.d/
