version: '3.6'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./www/rabbitmansion.com:/usr/share/nginx/html
      - ./nginx/:/etc/nginx/conf.d/
      - ./letsencrypt/well-known:/www/letsencrypt
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./etc/letsencrypt/live/rabbitmansion.com/fullchain.pem:/etc/letsencrypt/live/rabbitmansion.com/fullchain.pem
      - ./etc/letsencrypt/live/rabbitmansion.com/privkey.pem:/etc/letsencrypt/live/rabbitmansion.com/privkey.pem
      - ./node/:/app/
    networks:
      - docker-network

  networks:
    docker-network:
      driver: bridge

  nodejsreact:
    image: node:9.11.1-alpine
    container_name: nodejs
    environment:
      NODE_ENV: production
    working_dir: /home/app/serversiderender
    restart: always
    volumes:
          - ./node/serversiderender:/home/app/serversiderender

    expose:
      - 3000
    ports:
      - "3000:3000"
    command: "npm start"
