version: '3'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "433:433"

    expose:
      - 80
      - 433
    volumes:
      - ./www/example.com:/usr/share/nginx/html
      - ./nginx/:/etc/nginx/conf.d/
      - ./node/:/app/
      - ./letsencrypt/well-known:/www/letsencrypt
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - nodejsreact
    environment:
      - VIRTUAL_HOST=rabbitmansion.dev
  nodejsreact:
    image: node:9.11.1-alpine
    container_name: nodejs
    environment:
      NODE_ENV: production
    working_dir: /home/app/serversiderender
    restart: always
    volumes:
          - ./node/serversiderender:/home/app/serversiderender

    expose:
      - 3000
    ports:
      - "3000:3000"
    command: "npm start"
