version: '3'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    expose:
      - 80
    volumes:
      - ./web/html:/var/www/html/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOSTg
